const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const medications = [
  // === Category: Analgesics & Anti-inflammatory (مسكنات ومضادات الالتهاب) ===
  {
    name: "Panadol Advance 500mg",
    activeIngredient: "Paracetamol",
    manufacturer: "GSK",
    category: "Analgesic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "NSAID / Analgesic",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Panadol Extra",
    activeIngredient: "Paracetamol / Caffeine",
    manufacturer: "GSK",
    category: "Analgesic",
    strength: "500mg/65mg",
    form: "أقراص",
    therapeuticClass: "NSAID / Analgesic",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Panadol Joint 665mg",
    activeIngredient: "Paracetamol",
    manufacturer: "GSK",
    category: "Analgesic",
    strength: "665mg",
    form: "أقراص ممتدة المفعول",
    therapeuticClass: "NSAID / Analgesic",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Panadol Migraine",
    activeIngredient: "Paracetamol / Aspirin / Caffeine",
    manufacturer: "GSK",
    category: "Analgesic",
    strength: "250mg/250mg/65mg",
    form: "أقراص",
    therapeuticClass: "Migraine Remedy",
    route: "Oral",
    price: 50.0
  },
  {
    name: "Brufen 200mg",
    activeIngredient: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Analgesic",
    strength: "200mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 25.0
  },
  {
    name: "Brufen 400mg",
    activeIngredient: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Analgesic",
    strength: "400mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 40.0
  },
  {
    name: "Brufen 600mg",
    activeIngredient: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Analgesic",
    strength: "600mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 50.0
  },
  {
    name: "Brufen Syrup",
    activeIngredient: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Analgesic",
    strength: "100mg/5ml",
    form: "شراب",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Cataflam 25mg",
    activeIngredient: "Diclofenac Potassium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "25mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 35.0
  },
  {
    name: "Cataflam 50mg",
    activeIngredient: "Diclofenac Potassium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "50mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Cataflam 75mg Ampoule",
    activeIngredient: "Diclofenac Potassium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "75mg/3ml",
    form: "حقن عضلية",
    therapeuticClass: "NSAID / Injectable",
    route: "Intramuscular",
    price: 60.0
  },
  {
    name: "Voltaren 75mg Ampoule",
    activeIngredient: "Diclofenac Sodium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "75mg/3ml",
    form: "حقن عضلية",
    therapeuticClass: "NSAID / Injectable",
    route: "Intramuscular",
    price: 65.0
  },
  {
    name: "Voltaren 100mg Suppository",
    activeIngredient: "Diclofenac Sodium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "100mg",
    form: "لبوس شرجي",
    therapeuticClass: "NSAID / Suppository",
    route: "Rectal",
    price: 45.0
  },
  {
    name: "Voltaren Emulgel 100g",
    activeIngredient: "Diclofenac Diethylammonium",
    manufacturer: "Novartis",
    category: "Analgesic",
    strength: "1%",
    form: "جل موضعي",
    therapeuticClass: "NSAID / Topical Gel",
    route: "Topical",
    price: 120.0
  },
  {
    name: "Adolor 30mg Ampoule",
    activeIngredient: "Ketorolac Tromethamine",
    manufacturer: "Pharco",
    category: "Analgesic",
    strength: "30mg/1ml",
    form: "حقن",
    therapeuticClass: "NSAID / Potent Analgesic",
    route: "Intramuscular / Intravenous",
    price: 38.0
  },
  {
    name: "Ketofan 50mg",
    activeIngredient: "Ketoprofen",
    manufacturer: "Amriya",
    category: "Analgesic",
    strength: "50mg",
    form: "كبسولات",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 20.0
  },
  {
    name: "Ketofan 100mg",
    activeIngredient: "Ketoprofen",
    manufacturer: "Amriya",
    category: "Analgesic",
    strength: "100mg",
    form: "كبسولات",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 32.0
  },
  {
    name: "Feldene 20mg Capsule",
    activeIngredient: "Piroxicam",
    manufacturer: "Pfizer",
    category: "Analgesic",
    strength: "20mg",
    form: "كبسولات",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 42.0
  },
  {
    name: "Feldene Gel",
    activeIngredient: "Piroxicam",
    manufacturer: "Pfizer",
    category: "Analgesic",
    strength: "0.5%",
    form: "جل موضعي",
    therapeuticClass: "NSAID / Topical",
    route: "Topical",
    price: 30.0
  },
  {
    name: "Cetal 500mg",
    activeIngredient: "Paracetamol",
    manufacturer: "EPICO",
    category: "Analgesic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Analgesic / Antipyretic",
    route: "Oral",
    price: 15.0
  },
  {
    name: "Cetal Drops",
    activeIngredient: "Paracetamol",
    manufacturer: "EPICO",
    category: "Analgesic",
    strength: "100mg/ml",
    form: "نقط للفم للاطفال",
    therapeuticClass: "Analgesic / Antipyretic",
    route: "Oral",
    price: 18.0
  },
  {
    name: "Cetal Suspension",
    activeIngredient: "Paracetamol",
    manufacturer: "EPICO",
    category: "Analgesic",
    strength: "250mg/5ml",
    form: "شراب للأطفال",
    therapeuticClass: "Analgesic / Antipyretic",
    route: "Oral",
    price: 22.0
  },
  {
    name: "Novaldol 1000mg",
    activeIngredient: "Paracetamol",
    manufacturer: "Sanofi",
    category: "Analgesic",
    strength: "1000mg",
    form: "أقراص",
    therapeuticClass: "Analgesic / Antipyretic",
    route: "Oral",
    price: 40.0
  },
  {
    name: "Migranil",
    activeIngredient: "Ergotamine / Caffeine / Paracetamol",
    manufacturer: "ADWIA",
    category: "Analgesic",
    strength: "1mg/100mg/250mg",
    form: "أقراص",
    therapeuticClass: "Anti-Migraine",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Spasmo-Amigran",
    activeIngredient: "Ergotamine / Caffeine / Camylofin / Analgin",
    manufacturer: "Amriya",
    category: "Analgesic",
    strength: "1mg/100mg/10mg/500mg",
    form: "أقراص",
    therapeuticClass: "Anti-Migraine / Antispasmodic",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Celebrex 100mg",
    activeIngredient: "Celecoxib",
    manufacturer: "Pfizer",
    category: "Analgesic",
    strength: "100mg",
    form: "كبسولات",
    therapeuticClass: "Selective COX-2 Inhibitor",
    route: "Oral",
    price: 95.0
  },
  {
    name: "Celebrex 200mg",
    activeIngredient: "Celecoxib",
    manufacturer: "Pfizer",
    category: "Analgesic",
    strength: "200mg",
    form: "كبسولات",
    therapeuticClass: "Selective COX-2 Inhibitor",
    route: "Oral",
    price: 160.0
  },
  {
    name: "Arcoxia 60mg",
    activeIngredient: "Etoricoxib",
    manufacturer: "MSD",
    category: "Analgesic",
    strength: "60mg",
    form: "أقراص",
    therapeuticClass: "Selective COX-2 Inhibitor",
    route: "Oral",
    price: 130.0
  },
  {
    name: "Arcoxia 90mg",
    activeIngredient: "Etoricoxib",
    manufacturer: "MSD",
    category: "Analgesic",
    strength: "90mg",
    form: "أقراص",
    therapeuticClass: "Selective COX-2 Inhibitor",
    route: "Oral",
    price: 155.0
  },
  {
    name: "Arcoxia 120mg",
    activeIngredient: "Etoricoxib",
    manufacturer: "MSD",
    category: "Analgesic",
    strength: "120mg",
    form: "أقراص",
    therapeuticClass: "Selective COX-2 Inhibitor",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Lornoxicam 8mg",
    activeIngredient: "Lornoxicam",
    manufacturer: "Sigma",
    category: "Analgesic",
    strength: "8mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Melocam 15mg",
    activeIngredient: "Meloxicam",
    manufacturer: "Apex",
    category: "Analgesic",
    strength: "15mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Proxen 500mg",
    activeIngredient: "Naproxen",
    manufacturer: "Kahira",
    category: "Analgesic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "NSAID",
    route: "Oral",
    price: 52.0
  },

  // === Category: Antibiotics & Anti-infectives (المضادات الحيوية) ===
  {
    name: "Augmentin 1g",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "GSK",
    category: "Antibiotic",
    strength: "1g",
    form: "أقراص",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 120.0
  },
  {
    name: "Augmentin 625mg",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "GSK",
    category: "Antibiotic",
    strength: "625mg",
    form: "أقراص",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Augmentin Suspension 457mg",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "GSK",
    category: "Antibiotic",
    strength: "457mg/5ml",
    form: "معلق شراب للأطفال",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Curam 1g",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "Sandoz",
    category: "Antibiotic",
    strength: "1g",
    form: "أقراص",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 110.0
  },
  {
    name: "Curam Suspension 228mg",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "Sandoz",
    category: "Antibiotic",
    strength: "228.5mg/5ml",
    form: "معلق شراب للأطفال",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Flumox 1g",
    activeIngredient: "Amoxicillin / Flucloxacillin",
    manufacturer: "EPICO",
    category: "Antibiotic",
    strength: "1g",
    form: "أقراص",
    therapeuticClass: "Broad Spectrum Antibiotic",
    route: "Oral",
    price: 68.0
  },
  {
    name: "Flumox 500mg",
    activeIngredient: "Amoxicillin / Flucloxacillin",
    manufacturer: "EPICO",
    category: "Antibiotic",
    strength: "500mg",
    form: "كبسولات",
    therapeuticClass: "Broad Spectrum Antibiotic",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Megamox 1g",
    activeIngredient: "Amoxicillin / Clavulanic Acid",
    manufacturer: "Hikma",
    category: "Antibiotic",
    strength: "1g",
    form: "أقراص",
    therapeuticClass: "Penicillin Antibiotic",
    route: "Oral",
    price: 105.0
  },
  {
    name: "Amoxil 500mg Capsule",
    activeIngredient: "Amoxicillin",
    manufacturer: "GSK",
    category: "Antibiotic",
    strength: "500mg",
    form: "كبسولات",
    therapeuticClass: "Broad Spectrum Penicillin",
    route: "Oral",
    price: 38.0
  },
  {
    name: "Velosef 1g Capsule",
    activeIngredient: "Cephradine",
    manufacturer: "Squibb",
    category: "Antibiotic",
    strength: "1g",
    form: "كبسولات",
    therapeuticClass: "First-Generation Cephalosporin",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Velosef 500mg",
    activeIngredient: "Cephradine",
    manufacturer: "Squibb",
    category: "Antibiotic",
    strength: "500mg",
    form: "كبسولات",
    therapeuticClass: "First-Generation Cephalosporin",
    route: "Oral",
    price: 50.0
  },
  {
    name: "Duricef 1g",
    activeIngredient: "Cefadroxil",
    manufacturer: "Bristol-Myers Squibb",
    category: "Antibiotic",
    strength: "1g",
    form: "أقراص",
    therapeuticClass: "First-Generation Cephalosporin",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Cefotax 1g Injection",
    activeIngredient: "Cefotaxime",
    manufacturer: "EPICO",
    category: "Antibiotic",
    strength: "1g",
    form: "حقن وريد / عضل",
    therapeuticClass: "Third-Generation Cephalosporin",
    route: "Intravenous / Intramuscular",
    price: 45.0
  },
  {
    name: "Cefotax 500mg Injection",
    activeIngredient: "Cefotaxime",
    manufacturer: "EPICO",
    category: "Antibiotic",
    strength: "500mg",
    form: "حقن وريد / عضل",
    therapeuticClass: "Third-Generation Cephalosporin",
    route: "Intravenous / Intramuscular",
    price: 32.0
  },
  {
    name: "Keftrex 1g Injection",
    activeIngredient: "Ceftriaxone",
    manufacturer: "Pharco",
    category: "Antibiotic",
    strength: "1g",
    form: "حقن وريد / عضل",
    therapeuticClass: "Third-Generation Cephalosporin",
    route: "Intravenous / Intramuscular",
    price: 70.0
  },
  {
    name: "Zithromax 500mg",
    activeIngredient: "Azithromycin",
    manufacturer: "Pfizer",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Macrolide Antibiotic",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Zithromax Suspension",
    activeIngredient: "Azithromycin",
    manufacturer: "Pfizer",
    category: "Antibiotic",
    strength: "200mg/5ml",
    form: "معلق شراب للأطفال",
    therapeuticClass: "Macrolide Antibiotic",
    route: "Oral",
    price: 72.0
  },
  {
    name: "Klacid 500mg",
    activeIngredient: "Clarithromycin",
    manufacturer: "Abbott",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Macrolide Antibiotic",
    route: "Oral",
    price: 140.0
  },
  {
    name: "Ciprofar 500mg",
    activeIngredient: "Ciprofloxacin",
    manufacturer: "Pharco",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Fluoroquinolone Antibiotic",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Ciprofar 750mg",
    activeIngredient: "Ciprofloxacin",
    manufacturer: "Pharco",
    category: "Antibiotic",
    strength: "750mg",
    form: "أقراص",
    therapeuticClass: "Fluoroquinolone Antibiotic",
    route: "Oral",
    price: 68.0
  },
  {
    name: "Tavanic 500mg",
    activeIngredient: "Levofloxacin",
    manufacturer: "Sanofi",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Fluoroquinolone Antibiotic",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Vibramycin 100mg",
    activeIngredient: "Doxycycline",
    manufacturer: "Pfizer",
    category: "Antibiotic",
    strength: "100mg",
    form: "كبسولات",
    therapeuticClass: "Tetracycline Antibiotic",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Dalacin C 300mg",
    activeIngredient: "Clindamycin",
    manufacturer: "Pfizer",
    category: "Antibiotic",
    strength: "300mg",
    form: "كبسولات",
    therapeuticClass: "Lincosamide Antibiotic",
    route: "Oral",
    price: 135.0
  },
  {
    name: "Flagyl 500mg Tablet",
    activeIngredient: "Metronidazole",
    manufacturer: "Sanofi",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Antiprotozoal / Antibacterial",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Flagyl Syrup",
    activeIngredient: "Metronidazole Benzoate",
    manufacturer: "Sanofi",
    category: "Antibiotic",
    strength: "125mg/5ml",
    form: "شراب",
    therapeuticClass: "Antiprotozoal / Antibacterial",
    route: "Oral",
    price: 20.0
  },
  {
    name: "Amrizole 500mg",
    activeIngredient: "Metronidazole",
    manufacturer: "Amriya",
    category: "Antibiotic",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Antiprotozoal / Antibacterial",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Septrin DS",
    activeIngredient: "Sulfamethoxazole / Trimethoprim",
    manufacturer: "GSK",
    category: "Antibiotic",
    strength: "800mg/160mg",
    form: "أقراص",
    therapeuticClass: "Sulfonamide Antibiotic",
    route: "Oral",
    price: 36.0
  },

  // === Category: Cardiovascular & Antihypertensives (أدوية القلب والضغط) ===
  {
    name: "Concor 5mg",
    activeIngredient: "Bisoprolol Fumarate",
    manufacturer: "Merck",
    category: "Cardiovascular",
    strength: "5mg",
    form: "أقراص",
    therapeuticClass: "Beta-Blocker",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Concor 2.5mg",
    activeIngredient: "Bisoprolol Fumarate",
    manufacturer: "Merck",
    category: "Cardiovascular",
    strength: "2.5mg",
    form: "أقراص",
    therapeuticClass: "Beta-Blocker",
    route: "Oral",
    price: 38.0
  },
  {
    name: "Concor 5mg Plus",
    activeIngredient: "Bisoprolol Fumarate / Hydrochlorothiazide",
    manufacturer: "Merck",
    category: "Cardiovascular",
    strength: "5mg/12.5mg",
    form: "أقراص",
    therapeuticClass: "Beta-Blocker & Diuretic",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Capoten 25mg",
    activeIngredient: "Captopril",
    manufacturer: "Squibb",
    category: "Cardiovascular",
    strength: "25mg",
    form: "أقراص",
    therapeuticClass: "ACE Inhibitor",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Capoten 50mg",
    activeIngredient: "Captopril",
    manufacturer: "Squibb",
    category: "Cardiovascular",
    strength: "50mg",
    form: "أقراص",
    therapeuticClass: "ACE Inhibitor",
    route: "Oral",
    price: 42.0
  },
  {
    name: "Zestril 10mg",
    activeIngredient: "Lisinopril",
    manufacturer: "AstraZeneca",
    category: "Cardiovascular",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "ACE Inhibitor",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Zestril 20mg",
    activeIngredient: "Lisinopril",
    manufacturer: "AstraZeneca",
    category: "Cardiovascular",
    strength: "20mg",
    form: "أقراص",
    therapeuticClass: "ACE Inhibitor",
    route: "Oral",
    price: 85.0
  },
  {
    name: "Exforge 5/160mg",
    activeIngredient: "Amlodipine / Valsartan",
    manufacturer: "Novartis",
    category: "Cardiovascular",
    strength: "5mg/160mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Calcium Channel Blocker & ARB",
    route: "Oral",
    price: 185.0
  },
  {
    name: "Exforge 10/160mg",
    activeIngredient: "Amlodipine / Valsartan",
    manufacturer: "Novartis",
    category: "Cardiovascular",
    strength: "10mg/160mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Calcium Channel Blocker & ARB",
    route: "Oral",
    price: 210.0
  },
  {
    name: "Atacand 16mg",
    activeIngredient: "Candesartan Cilexetil",
    manufacturer: "AstraZeneca",
    category: "Cardiovascular",
    strength: "16mg",
    form: "أقراص",
    therapeuticClass: "Angiotensin II Receptor Blocker (ARB)",
    route: "Oral",
    price: 110.0
  },
  {
    name: "Micardis 80mg",
    activeIngredient: "Telmisartan",
    manufacturer: "Boehringer Ingelheim",
    category: "Cardiovascular",
    strength: "80mg",
    form: "أقراص",
    therapeuticClass: "Angiotensin II Receptor Blocker (ARB)",
    route: "Oral",
    price: 160.0
  },
  {
    name: "Natrilix SR 1.5mg",
    activeIngredient: "Indapamide",
    manufacturer: "Servier",
    category: "Cardiovascular",
    strength: "1.5mg",
    form: "أقراص ممتدة المفعول",
    therapeuticClass: "Thiazide-like Diuretic",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Lasix 40mg",
    activeIngredient: "Furosemide",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "40mg",
    form: "أقراص",
    therapeuticClass: "Loop Diuretic",
    route: "Oral",
    price: 20.0
  },
  {
    name: "Lasix Ampoule 20mg",
    activeIngredient: "Furosemide",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "20mg/2ml",
    form: "حقن وريدية / عضلية",
    therapeuticClass: "Loop Diuretic",
    route: "Intravenous / Intramuscular",
    price: 30.0
  },
  {
    name: "Aldactone 100mg",
    activeIngredient: "Spironolactone",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "100mg",
    form: "أقراص",
    therapeuticClass: "Aldosterone Antagonist / Diuretic",
    route: "Oral",
    price: 85.0
  },
  {
    name: "Norvasc 5mg",
    activeIngredient: "Amlodipine Besylate",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "5mg",
    form: "أقراص",
    therapeuticClass: "Calcium Channel Blocker",
    route: "Oral",
    price: 120.0
  },
  {
    name: "Norvasc 10mg",
    activeIngredient: "Amlodipine Besylate",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Calcium Channel Blocker",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Adalat Retard 20mg",
    activeIngredient: "Nifedipine",
    manufacturer: "Bayer",
    category: "Cardiovascular",
    strength: "20mg",
    form: "أقراص ممتدة المفعول",
    therapeuticClass: "Calcium Channel Blocker",
    route: "Oral",
    price: 65.0
  },
  {
    name: "Aspirin Protect 100mg",
    activeIngredient: "Acetylsalicylic Acid",
    manufacturer: "Bayer",
    category: "Cardiovascular",
    strength: "100mg",
    form: "أقراص مغلفة معوياً",
    therapeuticClass: "Antiplatelet / Aspirin",
    route: "Oral",
    price: 25.0
  },
  {
    name: "Plavix 75mg",
    activeIngredient: "Clopidogrel Bisulfate",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "75mg",
    form: "أقراص",
    therapeuticClass: "Antiplatelet Agent",
    route: "Oral",
    price: 205.0
  },
  {
    name: "Clexane 40mg Injection",
    activeIngredient: "Enoxaparin Sodium",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "40mg/0.4ml",
    form: "حقن معبأة مسبقاً تحت الجلد",
    therapeuticClass: "Low Molecular Weight Heparin",
    route: "Subcutaneous",
    price: 140.0
  },
  {
    name: "Clexane 60mg Injection",
    activeIngredient: "Enoxaparin Sodium",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "60mg/0.6ml",
    form: "حقن معبأة مسبقاً تحت الجلد",
    therapeuticClass: "Low Molecular Weight Heparin",
    route: "Subcutaneous",
    price: 180.0
  },
  {
    name: "Lipitor 10mg",
    activeIngredient: "Atorvastatin Calcium",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Statin / Lipid Regulator",
    route: "Oral",
    price: 150.0
  },
  {
    name: "Lipitor 20mg",
    activeIngredient: "Atorvastatin Calcium",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "20mg",
    form: "أقراص",
    therapeuticClass: "Statin / Lipid Regulator",
    route: "Oral",
    price: 210.0
  },
  {
    name: "Lipitor 40mg",
    activeIngredient: "Atorvastatin Calcium",
    manufacturer: "Pfizer",
    category: "Cardiovascular",
    strength: "40mg",
    form: "أقراص",
    therapeuticClass: "Statin / Lipid Regulator",
    route: "Oral",
    price: 260.0
  },
  {
    name: "Crestor 10mg",
    activeIngredient: "Rosuvastatin Calcium",
    manufacturer: "AstraZeneca",
    category: "Cardiovascular",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Statin / Lipid Regulator",
    route: "Oral",
    price: 160.0
  },
  {
    name: "Crestor 20mg",
    activeIngredient: "Rosuvastatin Calcium",
    manufacturer: "AstraZeneca",
    category: "Cardiovascular",
    strength: "20mg",
    form: "أقراص",
    therapeuticClass: "Statin / Lipid Regulator",
    route: "Oral",
    price: 230.0
  },
  {
    name: "Lanoxin 0.25mg",
    activeIngredient: "Digoxin",
    manufacturer: "GSK",
    category: "Cardiovascular",
    strength: "0.25mg",
    form: "أقراص",
    therapeuticClass: "Cardiac Glycoside",
    route: "Oral",
    price: 22.0
  },
  {
    name: "Cordarone 200mg",
    activeIngredient: "Amiodarone Hydrochloride",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    strength: "200mg",
    form: "أقراص",
    therapeuticClass: "Anti-Arrhythmic",
    route: "Oral",
    price: 68.0
  },

  // === Category: Gastrointestinal (أدوية الجهاز الهضمي) ===
  {
    name: "Antinal Capsule 200mg",
    activeIngredient: "Nifuroxazide",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "200mg",
    form: "كبسولات",
    therapeuticClass: "Intestinal Antiseptic",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Antinal Syrup",
    activeIngredient: "Nifuroxazide",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "220mg/5ml",
    form: "شراب معلق للأطفال",
    therapeuticClass: "Intestinal Antiseptic",
    route: "Oral",
    price: 26.0
  },
  {
    name: "Streptoquin",
    activeIngredient: "Diiodohydroxyquinoline / Phthalylsulfathiazole / Streptomycin Sulfate",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "200mg/200mg/100mg",
    form: "أقراص",
    therapeuticClass: "Anti-diarrheal / Antispasmodic",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Controloc 40mg",
    activeIngredient: "Pantoprazole Sodium",
    manufacturer: "Takeda",
    category: "Gastrointestinal",
    strength: "40mg",
    form: "أقراص مقاومة لعصارة المعدة",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    route: "Oral",
    price: 135.0
  },
  {
    name: "Controloc 20mg",
    activeIngredient: "Pantoprazole Sodium",
    manufacturer: "Takeda",
    category: "Gastrointestinal",
    strength: "20mg",
    form: "أقراص مقاومة لعصارة المعدة",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Nexium 40mg",
    activeIngredient: "Esomeprazole",
    manufacturer: "AstraZeneca",
    category: "Gastrointestinal",
    strength: "40mg",
    form: "أقراص مقاومة لعصارة المعدة",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    route: "Oral",
    price: 220.0
  },
  {
    name: "Nexium 20mg",
    activeIngredient: "Esomeprazole",
    manufacturer: "AstraZeneca",
    category: "Gastrointestinal",
    strength: "20mg",
    form: "أقراص مقاومة لعصارة المعدة",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    route: "Oral",
    price: 155.0
  },
  {
    name: "Omez 20mg Capsule",
    activeIngredient: "Omeprazole",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "20mg",
    form: "كبسولات مغلفة معوياً",
    therapeuticClass: "Proton Pump Inhibitor (PPI)",
    route: "Oral",
    price: 33.0
  },
  {
    name: "Antodine 40mg",
    activeIngredient: "Famotidine",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "40mg",
    form: "أقراص",
    therapeuticClass: "H2-Receptor Antagonist",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Spasmo-Digestin",
    activeIngredient: "Dicyclomine / Papain / Sanzyme / Dehydrocholic Acid",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "Complex",
    form: "أقراص",
    therapeuticClass: "Digestive Enzymes & Antispasmodic",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Digestin",
    activeIngredient: "Pepsin / Sanzyme",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "Complex",
    form: "أقراص",
    therapeuticClass: "Digestive Enzymes",
    route: "Oral",
    price: 22.0
  },
  {
    name: "Motilium 10mg",
    activeIngredient: "Domperidone",
    manufacturer: "Janssen",
    category: "Gastrointestinal",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Antiemetic / Prokinetic",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Gastreg 200mg",
    activeIngredient: "Trimebutine Maleate",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "200mg",
    form: "أقراص",
    therapeuticClass: "Gastrointestinal Regulator",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Primeperan 10mg",
    activeIngredient: "Metoclopramide Hydrochloride",
    manufacturer: "Sanofi",
    category: "Gastrointestinal",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Antiemetic / Dopamine Antagonist",
    route: "Oral",
    price: 18.0
  },
  {
    name: "Mucogel Suspension 180ml",
    activeIngredient: "Magnesium Hydroxide / Aluminium Hydroxide",
    manufacturer: "EPICO",
    category: "Gastrointestinal",
    strength: "Complex",
    form: "شراب معلق مضاد للحموضة",
    therapeuticClass: "Antacid",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Epicogel Suspension",
    activeIngredient: "Aluminium Hydroxide / Magnesium Hydroxide / Dimethicone",
    manufacturer: "EPICO",
    category: "Gastrointestinal",
    strength: "Complex",
    form: "شراب مضاد للحموضة والانتفاخ",
    therapeuticClass: "Antacid & Antiflatulent",
    route: "Oral",
    price: 26.0
  },
  {
    name: "Gaviscon Liquid 150ml",
    activeIngredient: "Sodium Alginate / Sodium Bicarbonate / Calcium Carbonate",
    manufacturer: "Reckitt Benckiser",
    category: "Gastrointestinal",
    strength: "Complex",
    form: "شراب معلق لعلاج ارتجاع المريء",
    therapeuticClass: "Antacid / Reflux Barrier",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Duspatalin Retard 200mg",
    activeIngredient: "Mebeverine Hydrochloride",
    manufacturer: "Abbott",
    category: "Gastrointestinal",
    strength: "200mg",
    form: "كبسولات ممتدة المفعول",
    therapeuticClass: "Antispasmodic for IBS",
    route: "Oral",
    price: 85.0
  },
  {
    name: "Coloverin D",
    activeIngredient: "Mebeverine Hydrochloride / Dimethicone",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "135mg/40mg",
    form: "أقراص",
    therapeuticClass: "Antispasmodic / Antiflatulent for IBS",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Coloverin SR",
    activeIngredient: "Mebeverine Hydrochloride",
    manufacturer: "Pharco",
    category: "Gastrointestinal",
    strength: "200mg",
    form: "أقراص ممتدة المفعول",
    therapeuticClass: "Antispasmodic for IBS",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Librax",
    activeIngredient: "Chlordiazepoxide / Clidinium Bromide",
    manufacturer: "Roche",
    category: "Gastrointestinal",
    strength: "5mg/2.5mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Anxiolytic / Antispasmodic for Colon",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Visceralgine Tablets",
    activeIngredient: "Tiemonium Methylsulfate",
    manufacturer: "Sedico",
    category: "Gastrointestinal",
    strength: "50mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Antispasmodic",
    route: "Oral",
    price: 32.0
  },
  {
    name: "Duphalac Syrup 200ml",
    activeIngredient: "Lactulose",
    manufacturer: "Abbott",
    category: "Gastrointestinal",
    strength: "66.7g/100ml",
    form: "شراب ملين",
    therapeuticClass: "Osmotic Laxative",
    route: "Oral",
    price: 68.0
  },

  // === Category: Respiratory & Antihistamines (أدوية الجهاز التنفسي والحساسية) ===
  {
    name: "Ventolin Inhaler",
    activeIngredient: "Salbutamol (Albuterol)",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "100mcg/dose",
    form: "بخاخة صدر",
    therapeuticClass: "Bronchodilator (SABA)",
    route: "Inhalation",
    price: 85.0
  },
  {
    name: "Ventolin Syrup",
    activeIngredient: "Salbutamol",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "2mg/5ml",
    form: "شراب موسع للشعب الهوائية",
    therapeuticClass: "Bronchodilator (SABA)",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Ventolin Respirator Solution",
    activeIngredient: "Salbutamol",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "5mg/ml (0.5%)",
    form: "محلول جلسات استنشاق بخار",
    therapeuticClass: "Bronchodilator",
    route: "Inhalation via Nebulizer",
    price: 50.0
  },
  {
    name: "Farcolin Nebulizer Solution",
    activeIngredient: "Salbutamol",
    manufacturer: "Pharco",
    category: "Respiratory",
    strength: "0.5%",
    form: "محلول جلسات استنشاق بخار",
    therapeuticClass: "Bronchodilator",
    route: "Inhalation via Nebulizer",
    price: 25.0
  },
  {
    name: "Symbicort Inhaler 160/4.5",
    activeIngredient: "Budesonide / Formoterol Fumarate",
    manufacturer: "AstraZeneca",
    category: "Respiratory",
    strength: "160mcg/4.5mcg",
    form: "بودرة استنشاق معبأة بالجرعة Turbuhaler",
    therapeuticClass: "Inhaled Corticosteroid & LABA",
    route: "Inhalation",
    price: 280.0
  },
  {
    name: "Seretide Evohaler 125mg",
    activeIngredient: "Fluticasone Propionate / Salmeterol",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "125mcg/25mcg",
    form: "بخاخة صدر بجرعات مقننة",
    therapeuticClass: "Inhaled Corticosteroid & LABA",
    route: "Inhalation",
    price: 260.0
  },
  {
    name: "Singulair 10mg",
    activeIngredient: "Montelukast Sodium",
    manufacturer: "MSD",
    category: "Respiratory",
    strength: "10mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Leukotriene Receptor Antagonist",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Singulair 5mg Pediatric",
    activeIngredient: "Montelukast Sodium",
    manufacturer: "MSD",
    category: "Respiratory",
    strength: "5mg",
    form: "أقراص مضغ للأطفال",
    therapeuticClass: "Leukotriene Receptor Antagonist",
    route: "Oral",
    price: 150.0
  },
  {
    name: "Zyrtec 10mg",
    activeIngredient: "Cetirizine Hydrochloride",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "10mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Zyrtec Drops 10ml",
    activeIngredient: "Cetirizine Hydrochloride",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "10mg/ml",
    form: "نقط للحساسية للفم للأطفال",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Zyrtec Syrup",
    activeIngredient: "Cetirizine Hydrochloride",
    manufacturer: "GSK",
    category: "Respiratory",
    strength: "5mg/5ml",
    form: "شراب مضاد للحساسية للأطفال",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 32.0
  },
  {
    name: "Kestine 10mg",
    activeIngredient: "Ebastine",
    manufacturer: "Almirall",
    category: "Respiratory",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Claritine 10mg",
    activeIngredient: "Loratadine",
    manufacturer: "Bayer",
    category: "Respiratory",
    strength: "10mg",
    form: "أقراص",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Telfast 120mg",
    activeIngredient: "Fexofenadine Hydrochloride",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "120mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Telfast 180mg",
    activeIngredient: "Fexofenadine Hydrochloride",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "180mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Second-Generation Antihistamine (High Potency)",
    route: "Oral",
    price: 110.0
  },
  {
    name: "Aerius 5mg",
    activeIngredient: "Desloratadine",
    manufacturer: "Organon",
    category: "Respiratory",
    strength: "5mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Second-Generation Antihistamine",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Selgon Tablets",
    activeIngredient: "Pipazethate Hydrochloride",
    manufacturer: "EPICO",
    category: "Respiratory",
    strength: "20mg",
    form: "أقراص مهدئة للسعال",
    therapeuticClass: "Antitussive / Cough Suppressant",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Selgon Drops 15ml",
    activeIngredient: "Pipazethate",
    manufacturer: "EPICO",
    category: "Respiratory",
    strength: "40mg/ml",
    form: "نقط مهدئة للسعال للفم",
    therapeuticClass: "Antitussive / Cough Suppressant",
    route: "Oral",
    price: 20.0
  },
  {
    name: "Sinecod Syrup 200ml",
    activeIngredient: "Butamirate Citrate",
    manufacturer: "Novartis",
    category: "Respiratory",
    strength: "1.5mg/ml",
    form: "شراب مهدئ للسعال الجاف",
    therapeuticClass: "Centrally Acting Antitussive",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Bronchicum Elixir Syrup",
    activeIngredient: "Thyme Extract / Primula Root Extract",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "Natural Complex",
    form: "شراب طارد للبلغم ومذيب",
    therapeuticClass: "Herbal Mucolytic / Expectorant",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Otrivin Adult Nasal Spray",
    activeIngredient: "Xylometazoline Hydrochloride",
    manufacturer: "Novartis",
    category: "Respiratory",
    strength: "0.1%",
    form: "بخاخة للأنف للبالغين مضادة للاحتقان",
    therapeuticClass: "Nasal Decongestant",
    route: "Nasal Spray",
    price: 25.0
  },
  {
    name: "Otrivin Child Nasal Drops",
    activeIngredient: "Xylometazoline",
    manufacturer: "Novartis",
    category: "Respiratory",
    strength: "0.05%",
    form: "نقط للأنف للأطفال مضادة للاحتقان",
    therapeuticClass: "Nasal Decongestant",
    route: "Nasal Drops",
    price: 20.0
  },
  {
    name: "Otrivin Baby Saline Spray",
    activeIngredient: "Sodium Chloride",
    manufacturer: "Novartis",
    category: "Respiratory",
    strength: "0.74%",
    form: "بخاخ أنف معقم للأطفال والرضع",
    therapeuticClass: "Nasal Saline Wash / Moisturizer",
    route: "Nasal Spray",
    price: 35.0
  },
  {
    name: "Solupred 20mg soluble",
    activeIngredient: "Prednisolone Sodium Phosphate",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "20mg",
    form: "أقراص قابلة للذوبان للفم",
    therapeuticClass: "Systemic Corticosteroid",
    route: "Oral",
    price: 68.0
  },
  {
    name: "Solupred 5mg soluble",
    activeIngredient: "Prednisolone Sodium Phosphate",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "5mg",
    form: "أقراص قابلة للذوبان للفم",
    therapeuticClass: "Systemic Corticosteroid",
    route: "Oral",
    price: 40.0
  },
  {
    name: "Hostacortin H 5mg",
    activeIngredient: "Prednisolone",
    manufacturer: "Sanofi",
    category: "Respiratory",
    strength: "5mg",
    form: "أقراص",
    therapeuticClass: "Corticosteroid",
    route: "Oral",
    price: 18.0
  },

  // === Category: Diabetes & Endocrine (أدوية السكري والغدد) ===
  {
    name: "Glucophage 1000mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "Merck",
    category: "Endocrine",
    strength: "1000mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Oral Antidiabetic (Biguanide)",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Glucophage XR 1000mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "Merck",
    category: "Endocrine",
    strength: "1000mg",
    form: "أقراص ممتدة المفعول",
    therapeuticClass: "Oral Antidiabetic (Biguanide)",
    route: "Oral",
    price: 80.0
  },
  {
    name: "Glucophage 500mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "Merck",
    category: "Endocrine",
    strength: "500mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Oral Antidiabetic (Biguanide)",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Cidophage 1000mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "CID",
    category: "Endocrine",
    strength: "1000mg",
    form: "أقراص",
    therapeuticClass: "Oral Antidiabetic",
    route: "Oral",
    price: 24.0
  },
  {
    name: "Cidophage 500mg",
    activeIngredient: "Metformin Hydrochloride",
    manufacturer: "CID",
    category: "Endocrine",
    strength: "500mg",
    form: "أقراص",
    therapeuticClass: "Oral Antidiabetic",
    route: "Oral",
    price: 16.0
  },
  {
    name: "Diamicron 60mg MR",
    activeIngredient: "Gliclazide",
    manufacturer: "Servier",
    category: "Endocrine",
    strength: "60mg",
    form: "أقراص معدلة الإفراز",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 85.0
  },
  {
    name: "Diamicron 30mg MR",
    activeIngredient: "Gliclazide",
    manufacturer: "Servier",
    category: "Endocrine",
    strength: "30mg",
    form: "أقراص معدلة الإفراز",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Amaryl 1mg",
    activeIngredient: "Glimepiride",
    manufacturer: "Sanofi",
    category: "Endocrine",
    strength: "1mg",
    form: "أقراص",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Amaryl 2mg",
    activeIngredient: "Glimepiride",
    manufacturer: "Sanofi",
    category: "Endocrine",
    strength: "2mg",
    form: "أقراص",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Amaryl 3mg",
    activeIngredient: "Glimepiride",
    manufacturer: "Sanofi",
    category: "Endocrine",
    strength: "3mg",
    form: "أقراص",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 64.0
  },
  {
    name: "Amaryl 4mg",
    activeIngredient: "Glimepiride",
    manufacturer: "Sanofi",
    category: "Endocrine",
    strength: "4mg",
    form: "أقراص",
    therapeuticClass: "Sulfonylurea Antidiabetic",
    route: "Oral",
    price: 78.0
  },
  {
    name: "Januvia 100mg",
    activeIngredient: "Sitagliptin Phosphate",
    manufacturer: "MSD",
    category: "Endocrine",
    strength: "100mg",
    form: "أقراص مغلفة",
    therapeuticClass: "DPP-4 Inhibitor Antidiabetic",
    route: "Oral",
    price: 195.0
  },
  {
    name: "Januvia 50mg",
    activeIngredient: "Sitagliptin Phosphate",
    manufacturer: "MSD",
    category: "Endocrine",
    strength: "50mg",
    form: "أقراص مغلفة",
    therapeuticClass: "DPP-4 Inhibitor Antidiabetic",
    route: "Oral",
    price: 140.0
  },
  {
    name: "Galvus 50mg",
    activeIngredient: "Vildagliptin",
    manufacturer: "Novartis",
    category: "Endocrine",
    strength: "50mg",
    form: "أقراص",
    therapeuticClass: "DPP-4 Inhibitor Antidiabetic",
    route: "Oral",
    price: 120.0
  },
  {
    name: "Galvus Met 50/1000mg",
    activeIngredient: "Vildagliptin / Metformin Hydrochloride",
    manufacturer: "Novartis",
    category: "Endocrine",
    strength: "50mg/1000mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Combination Oral Antidiabetic",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Galvus Met 50/850mg",
    activeIngredient: "Vildagliptin / Metformin Hydrochloride",
    manufacturer: "Novartis",
    category: "Endocrine",
    strength: "50mg/850mg",
    form: "أقراص مغلفة",
    therapeuticClass: "Combination Oral Antidiabetic",
    route: "Oral",
    price: 165.0
  },
  {
    name: "Jardiance 10mg",
    activeIngredient: "Empagliflozin",
    manufacturer: "Boehringer Ingelheim",
    category: "Endocrine",
    strength: "10mg",
    form: "أقراص مغلفة",
    therapeuticClass: "SGLT-2 Inhibitor Antidiabetic",
    route: "Oral",
    price: 240.0
  },
  {
    name: "Jardiance 25mg",
    activeIngredient: "Empagliflozin",
    manufacturer: "Boehringer Ingelheim",
    category: "Endocrine",
    strength: "25mg",
    form: "أقراص مغلفة",
    therapeuticClass: "SGLT-2 Inhibitor Antidiabetic",
    route: "Oral",
    price: 310.0
  },
  {
    name: "Forxiga 10mg",
    activeIngredient: "Dapagliflozin",
    manufacturer: "AstraZeneca",
    category: "Endocrine",
    strength: "10mg",
    form: "أقراص مغلفة",
    therapeuticClass: "SGLT-2 Inhibitor Antidiabetic",
    route: "Oral",
    price: 225.0
  },
  {
    name: "Lantus SoloStar Pen",
    activeIngredient: "Insulin Glargine",
    manufacturer: "Sanofi",
    category: "Endocrine",
    strength: "100 U/ml",
    form: "قلم أنسولين معبأ مسبقاً ممتد المفعول",
    therapeuticClass: "Long-Acting Analog Insulin",
    route: "Subcutaneous",
    price: 360.0
  },
  {
    name: "Mixtard 30 Penfill",
    activeIngredient: "Insulin Human (Bi-phasic Isophane)",
    manufacturer: "Novo Nordisk",
    category: "Endocrine",
    strength: "100 IU/ml",
    form: "خراطيش أقلام أنسولين معلق مختلط",
    therapeuticClass: "Intermediate & Rapid-Acting Insulin Mix",
    route: "Subcutaneous",
    price: 160.0
  },
  {
    name: "NovoRapid FlexPen",
    activeIngredient: "Insulin Aspart",
    manufacturer: "Novo Nordisk",
    category: "Endocrine",
    strength: "100 U/ml",
    form: "قلم أنسولين سريع المفعول معبأ مسبقاً",
    therapeuticClass: "Rapid-Acting Analog Insulin",
    route: "Subcutaneous",
    price: 250.0
  },
  {
    name: "Euthyrox 50mcg",
    activeIngredient: "Levothyroxine Sodium",
    manufacturer: "Merck",
    category: "Endocrine",
    strength: "50mcg",
    form: "أقراص",
    therapeuticClass: "Thyroid Hormone replacement",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Euthyrox 100mcg",
    activeIngredient: "Levothyroxine Sodium",
    manufacturer: "Merck",
    category: "Endocrine",
    strength: "100mcg",
    form: "أقراص",
    therapeuticClass: "Thyroid Hormone replacement",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Carbimazole 5mg",
    activeIngredient: "Carbimazole",
    manufacturer: "CID",
    category: "Endocrine",
    strength: "5mg",
    form: "أقراص لعلاج فرط نشاط الغدة الدرقية",
    therapeuticClass: "Antithyroid Agent",
    route: "Oral",
    price: 30.0
  },
  {
    name: "Aldomet 250mg",
    activeIngredient: "Methyldopa",
    manufacturer: "Kahira / MSD",
    category: "Endocrine",
    strength: "250mg",
    form: "أقراص لعلاج الضغط لدى الحوامل",
    therapeuticClass: "Centrally Acting Alpha-2 Adrenergic Agonist",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Dostinex 0.5mg",
    activeIngredient: "Cabergoline",
    manufacturer: "Pfizer",
    category: "Endocrine",
    strength: "0.5mg",
    form: "أقراص لعلاج هرمون البرولاكتين",
    therapeuticClass: "Dopamine Receptor Agonist",
    route: "Oral",
    price: 190.0
  },
  // === Category: Vitamins, Minerals & Supplements (الفيتامينات والمكملات الغذائية) ===
  {
    name: "Neurobion Ampoule",
    activeIngredient: "Vitamin B1 + B6 + B12",
    manufacturer: "Merck",
    category: "Supplement",
    strength: "100mg/100mg/1mg",
    form: "حقن أمبولات",
    therapeuticClass: "Vitamin B Complex",
    route: "Intramuscular",
    price: 54.0
  },
  {
    name: "Neuroton Tablet",
    activeIngredient: "Vitamin B1 + B2 + B6 + B12 + Folic Acid",
    manufacturer: "Amriya",
    category: "Supplement",
    strength: "Complex",
    form: "أقراص مغلفة",
    therapeuticClass: "Vitamin B Complex",
    route: "Oral",
    price: 37.5
  },
  {
    name: "Milga Tablet",
    activeIngredient: "Benfotiamine (B1) / Pyridoxine (B6) / Cyanocobalamin (B12)",
    manufacturer: "Eva Pharma",
    category: "Supplement",
    strength: "40mg/60mg/250mcg",
    form: "أقراص مغلفة",
    therapeuticClass: "Neurotropic Vitamin B",
    route: "Oral",
    price: 42.0
  },
  {
    name: "Milga Advance Tablet",
    activeIngredient: "Benfotiamine (B1) / Pyridoxine (B6) / Cyanocobalamin (B12)",
    manufacturer: "Eva Pharma",
    category: "Supplement",
    strength: "300mg/100mg/250mcg",
    form: "أقراص مغلفة",
    therapeuticClass: "High Potency Neurotropic Vitamin B",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Osteocare Tablet",
    activeIngredient: "Calcium / Magnesium / Zinc / Vitamin D3",
    manufacturer: "Vitabiotics",
    category: "Supplement",
    strength: "Complex",
    form: "أقراص مكمل غذائي",
    therapeuticClass: "Bone Health Supplement",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Osteocare Syrup 120ml",
    activeIngredient: "Calcium / Magnesium / Zinc / Vitamin D3",
    manufacturer: "Vitabiotics",
    category: "Supplement",
    strength: "Complex",
    form: "شراب مكمل غذائي للأطفال",
    therapeuticClass: "Bone Health Supplement",
    route: "Oral",
    price: 50.0
  },
  {
    name: "Sansovit Syrup 120ml",
    activeIngredient: "Multi-Vitamins with Calcium",
    manufacturer: "August Pharma",
    category: "Supplement",
    strength: "Complex",
    form: "شراب فيتامينات للأطفال",
    therapeuticClass: "Pediatric Multi-Vitamin",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Vitacid C 1g Effervescent",
    activeIngredient: "Vitamin C (Ascorbic Acid)",
    manufacturer: "CID",
    category: "Supplement",
    strength: "1000mg",
    form: "أقراص فوارة",
    therapeuticClass: "Vitamin C Supplement",
    route: "Oral (After dissolution)",
    price: 24.0
  },
  {
    name: "Feroglobin Capsule",
    activeIngredient: "Iron / Zinc / Copper / Vitamin B Complex / Folic Acid",
    manufacturer: "Vitabiotics",
    category: "Supplement",
    strength: "Complex",
    form: "كبسولات مكملة للحديد",
    therapeuticClass: "Hematinic / Anti-Anemic",
    route: "Oral",
    price: 90.0
  },
  {
    name: "Feroglobin Liquid 120ml",
    activeIngredient: "Iron / Zinc / Vitamin B Complex / Minerals",
    manufacturer: "Vitabiotics",
    category: "Supplement",
    strength: "Complex",
    form: "شراب حديد وفيتامينات للأطفال",
    therapeuticClass: "Hematinic / Anti-Anemic",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Centrum Lutein",
    activeIngredient: "Multivitamins & Minerals with Lutein",
    manufacturer: "Pfizer",
    category: "Supplement",
    strength: "Complex",
    form: "أقراص",
    therapeuticClass: "Complete Multivitamin",
    route: "Oral",
    price: 250.0
  },
  {
    name: "Royal Vit G Capsule",
    activeIngredient: "Ginseng / Royal Jelly / Multivitamins & Minerals",
    manufacturer: "SEDICO",
    category: "Supplement",
    strength: "Complex",
    form: "كبسولات جيلاتينية رخوة",
    therapeuticClass: "Energy & Vitality Supplement",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Kerovit Capsule",
    activeIngredient: "46 Multivitamins, Minerals, and Active Herbs",
    manufacturer: "Amriya",
    category: "Supplement",
    strength: "Complex",
    form: "كبسولات جيلاتينية رخوة",
    therapeuticClass: "Comprehensive Multivitamin",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Depovit B12 1000mcg Ampoule",
    activeIngredient: "Hydroxocobalamin",
    manufacturer: "Amriya",
    category: "Supplement",
    strength: "1000mcg/2ml",
    form: "حقن أمبولات طويلة المفعول",
    therapeuticClass: "Vitamin B12 Injectable",
    route: "Intramuscular",
    price: 45.0
  },
  {
    name: "Vidrop Oral Drops 15ml",
    activeIngredient: "Vitamin D3 (Cholecalciferol)",
    manufacturer: "APICO",
    category: "Supplement",
    strength: "2800 IU/ml",
    form: "نقط للفم لعلاج نقص فيتامين د",
    therapeuticClass: "Vitamin D Supplement",
    route: "Oral",
    price: 20.0
  },

  // === Category: Dermatologicals (كريمات ومراهم الجلدية) ===
  {
    name: "Fucidin Cream 15g",
    activeIngredient: "Fusidic Acid",
    manufacturer: "LEO Pharma",
    category: "Dermatological",
    strength: "2%",
    form: "كريم مضاد حيوي موضعي",
    therapeuticClass: "Topical Antibiotic",
    route: "Topical",
    price: 38.0
  },
  {
    name: "Fucidin Ointment 15g",
    activeIngredient: "Sodium Fusidate",
    manufacturer: "LEO Pharma",
    category: "Dermatological",
    strength: "2%",
    form: "مرهم مضاد حيوي موضعي",
    therapeuticClass: "Topical Antibiotic",
    route: "Topical",
    price: 38.0
  },
  {
    name: "Fucicort Cream 15g",
    activeIngredient: "Fusidic Acid / Betamethasone Valerate",
    manufacturer: "LEO Pharma",
    category: "Dermatological",
    strength: "2%/0.1%",
    form: "كريم مضاد حيوي ومضاد للالتهاب",
    therapeuticClass: "Topical Corticosteroid & Antibiotic",
    route: "Topical",
    price: 52.0
  },
  {
    name: "Kenacomb Cream 15g",
    activeIngredient: "Triamcinolone / Neomycin / Gramicidin / Nystatin",
    manufacturer: "Squibb",
    category: "Dermatological",
    strength: "Complex",
    form: "كريم موضعي لعلاج الالتهابات والعدوى",
    therapeuticClass: "Topical Steroid / Antibacterial / Antifungal",
    route: "Topical",
    price: 32.0
  },
  {
    name: "Kenacomb Ointment 15g",
    activeIngredient: "Triamcinolone / Neomycin / Gramicidin / Nystatin",
    manufacturer: "Squibb",
    category: "Dermatological",
    strength: "Complex",
    form: "مرهم موضعي لعلاج الالتهابات والعدوى",
    therapeuticClass: "Topical Steroid / Antibacterial / Antifungal",
    route: "Topical",
    price: 32.0
  },
  {
    name: "Betaderm Cream 15g",
    activeIngredient: "Betamethasone Valerate",
    manufacturer: "EPICO",
    category: "Dermatological",
    strength: "0.1%",
    form: "كريم موضعي مضاد للحساسية والالتهاب",
    therapeuticClass: "Topical Corticosteroid",
    route: "Topical",
    price: 15.0
  },
  {
    name: "Quadriderm Cream 15g",
    activeIngredient: "Betamethasone / Gentamicin / Tolnaftate / Clioquinol",
    manufacturer: "Organon",
    category: "Dermatological",
    strength: "Complex",
    form: "كريم موضعي واسع المدى للجلد",
    therapeuticClass: "Corticosteroid / Anti-infective Combination",
    route: "Topical",
    price: 35.0
  },
  {
    name: "Daktacort Cream 15g",
    activeIngredient: "Miconazole Nitrate / Hydrocortisone",
    manufacturer: "Janssen",
    category: "Dermatological",
    strength: "2%/1%",
    form: "كريم مضاد للفطريات والالتهاب",
    therapeuticClass: "Topical Antifungal & Steroid",
    route: "Topical",
    price: 40.0
  },
  {
    name: "Daktarin Oral Gel 40g",
    activeIngredient: "Miconazole",
    manufacturer: "Janssen",
    category: "Dermatological",
    strength: "2% (20mg/g)",
    form: "جل للفم لعلاج الفطريات",
    therapeuticClass: "Oral Antifungal Gel",
    route: "Oral / Topical Buccal",
    price: 45.0
  },
  {
    name: "Miconaz Oral Gel 20g",
    activeIngredient: "Miconazole",
    manufacturer: "MUP",
    category: "Dermatological",
    strength: "2%",
    form: "جل للفم لعلاج فطريات الفم واللسان",
    therapeuticClass: "Oral Antifungal Gel",
    route: "Oral / Topical Buccal",
    price: 20.0
  },
  {
    name: "Panthenol Cream 20g",
    activeIngredient: "D-Panthenol",
    manufacturer: "The Nile",
    category: "Dermatological",
    strength: "2%",
    form: "كريم مرطب وملطف للجلد",
    therapeuticClass: "Emollient / Skin Protectant",
    route: "Topical",
    price: 18.0
  },
  {
    name: "Bepanthen Ointment 30g",
    activeIngredient: "Dexpanthenol",
    manufacturer: "Bayer",
    category: "Dermatological",
    strength: "5%",
    form: "مرهم لترطيب الجلد والتهابات الحفاضات",
    therapeuticClass: "Skin Protectant / Moisturizer",
    route: "Topical",
    price: 90.0
  },
  {
    name: "Dermovate Cream 25g",
    activeIngredient: "Clobetasol Propionate",
    manufacturer: "GSK",
    category: "Dermatological",
    strength: "0.05%",
    form: "كريم قوي جداً لعلاج الالتهابات الجلدية المستعصية",
    therapeuticClass: "Super-High Potency Topical Corticosteroid",
    route: "Topical",
    price: 45.0
  },
  {
    name: "Elocon Cream 30g",
    activeIngredient: "Mometasone Furoate",
    manufacturer: "Organon",
    category: "Dermatological",
    strength: "0.1%",
    form: "كريم موضعي للحساسية والأكزيما",
    therapeuticClass: "Medium Potency Topical Corticosteroid",
    route: "Topical",
    price: 80.0
  },

  // === Category: Ophthalmic & Otic Preparations (نقط العين والأذن) ===
  {
    name: "Tobradex Eye Drops",
    activeIngredient: "Tobramycin / Dexamethasone",
    manufacturer: "Alcon",
    category: "Ophthalmic",
    strength: "0.3%/0.1%",
    form: "قطرة معقمة للعين مضاد حيوي ومضاد التهاب",
    therapeuticClass: "Ophthalmic Antibiotic & Corticosteroid",
    route: "Ophthalmic (Eye)",
    price: 75.0
  },
  {
    name: "Tobrex Eye Drops",
    activeIngredient: "Tobramycin",
    manufacturer: "Alcon",
    category: "Ophthalmic",
    strength: "0.3%",
    form: "قطرة عين مضاد حيوي معقمة",
    therapeuticClass: "Ophthalmic Antibiotic",
    route: "Ophthalmic (Eye)",
    price: 60.0
  },
  {
    name: "Tears Naturale Free Eye Drops",
    activeIngredient: "Dextran 70 / Hydroxypropyl Methylcellulose",
    manufacturer: "Alcon",
    category: "Ophthalmic",
    strength: "Complex",
    form: "قطرة دموع صناعية خالية من المواد الحافظة للعين",
    therapeuticClass: "Ocular Lubricant / Artificial Tears",
    route: "Ophthalmic (Eye)",
    price: 85.0
  },
  {
    name: "Systane Ultra Eye Drops 10ml",
    activeIngredient: "Polyethylene Glycol / Propylene Glycol",
    manufacturer: "Alcon",
    category: "Ophthalmic",
    strength: "Complex",
    form: "قطرة مرطبة متطورة لجفاف العين",
    therapeuticClass: "Ocular Lubricant / Artificial Tears",
    route: "Ophthalmic (Eye)",
    price: 180.0
  },
  {
    name: "Dexatobrin Eye Drops",
    activeIngredient: "Tobramycin / Dexamethasone",
    manufacturer: "Amriya",
    category: "Ophthalmic",
    strength: "0.3%/0.1%",
    form: "قطرة عين مضاد حيوي وكورتيزون",
    therapeuticClass: "Ophthalmic Antibiotic & Corticosteroid",
    route: "Ophthalmic (Eye)",
    price: 36.0
  },
  {
    name: "Otal Ear Drops 10ml",
    activeIngredient: "Framycetin Sulfate / Gramicidin / Dexamethasone / Cinchocaine",
    manufacturer: "Amriya",
    category: "Otic",
    strength: "Complex",
    form: "قطرة مسكنة ومضادة للالتهابات والعدوى للأذن",
    therapeuticClass: "Otic Antibacterial, Corticosteroid & Local Anesthetic",
    route: "Otic (Ear)",
    price: 24.0
  },
  {
    name: "Viotic Ear Drops 10ml",
    activeIngredient: "Flumethasone Pivalate / Clioquinol",
    manufacturer: "Amriya",
    category: "Otic",
    strength: "0.02%/1%",
    form: "قطرة لعلاج التهابات وفطريات الأذن الخارجية",
    therapeuticClass: "Otic Corticosteroid & Antifungal",
    route: "Otic (Ear)",
    price: 22.0
  },
  {
    name: "Dewax Ear Drops",
    activeIngredient: "Docusate Sodium",
    manufacturer: "Sigma",
    category: "Otic",
    strength: "0.5%",
    form: "نقط مذيبة لشمع الأذن",
    therapeuticClass: "Cerumenolytic / Ear Wax Softener",
    route: "Otic (Ear)",
    price: 18.0
  },
  {
    name: "Prisoline Eye/Nasal Drops",
    activeIngredient: "Naphazoline Hydrochloride / Chlorpheniramine Maleate",
    manufacturer: "Kahira",
    category: "Ophthalmic",
    strength: "0.05%/0.05%",
    form: "قطرة قابضة للأوعية ومضادة للحساسية للعين والأنف",
    therapeuticClass: "Ophthalmic / Nasal Decongestant & Antihistamine",
    route: "Ophthalmic (Eye) / Nasal",
    price: 20.0
  },
  {
    name: "Polyfresh Eye Drops",
    activeIngredient: "Sodium Hyaluronate",
    manufacturer: "Orchidia",
    category: "Ophthalmic",
    strength: "0.1%",
    form: "قطرة مرطبة لعلاج جفاف العين الشديد",
    therapeuticClass: "Ocular Lubricant / Sodium Hyaluronate",
    route: "Ophthalmic (Eye)",
    price: 90.0
  },

  // === Category: Urological & Renal (أدوية المسالك البولية والكلى والبروستاتا) ===
  {
    name: "Uralyt-U Granules 280g",
    activeIngredient: "Potassium Sodium Hydrogen Citrate",
    manufacturer: "Madaus / Amriya",
    category: "Urology",
    strength: "Complex",
    form: "حبيبات فوارة لعلاج وإذابة حصوات حمض اليوريك",
    therapeuticClass: "Urinary Alkalinizer / Stones Dissolver",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Epimag Effervescent Powder",
    activeIngredient: "Magnesium Citrate",
    manufacturer: "EPICO",
    category: "Urology",
    strength: "2.125g",
    form: "فوار لعلاج زيادة أملاح الأوكسالات في البول",
    therapeuticClass: "Urinary Supplement / Oxalate Stones Preventer",
    route: "Oral",
    price: 15.0
  },
  {
    name: "Rowatinex Capsule",
    activeIngredient: "Essential Oils (Anethol, Borneol, Camphene, Cineol, Fenchone, Pinene)",
    manufacturer: "Amriya",
    category: "Urology",
    strength: "Complex",
    form: "كبسولات طاردة لحصوات الحالب ومطهرة للمسالك",
    therapeuticClass: "Renal Antispasmodic & Litholytic",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Rowachol Capsule",
    activeIngredient: "Essential Oils (Menthol, Menthone, Pinene, Borneol, Camphene, Cineol)",
    manufacturer: "Amriya",
    category: "Urology",
    strength: "Complex",
    form: "كبسولات لإذابة ومنع حصوات المرارة ومدرة للعصارة الصفراوية",
    therapeuticClass: "Choleretic & Cholelitholytic Agent",
    route: "Oral",
    price: 42.0
  },
  {
    name: "Cystone Tablet",
    activeIngredient: "Didymocarpus pedicellata / Saxifraga ligulata / Rubia cordifolia",
    manufacturer: "Himalaya",
    category: "Urology",
    strength: "Natural Complex",
    form: "أقراص عشبية لعلاج أملاح وحصوات الكلى",
    therapeuticClass: "Herbal Urinary Antiseptic & Litholytic",
    route: "Oral",
    price: 60.0
  },
  {
    name: "Omnic 0.4mg Capsule",
    activeIngredient: "Tamsulosin Hydrochloride",
    manufacturer: "Astellas",
    category: "Urology",
    strength: "0.4mg",
    form: "كبسولات معدلة الإفراز لعلاج تضخم البروستاتا",
    therapeuticClass: "Alpha-1 Adrenergic Receptor Blocker",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Omnic Ocas 0.4mg Tablet",
    activeIngredient: "Tamsulosin Hydrochloride",
    manufacturer: "Astellas",
    category: "Urology",
    strength: "0.4mg",
    form: "أقراص ممتدة المفعول لعلاج تضخم البروستاتا",
    therapeuticClass: "Alpha-1 Adrenergic Receptor Blocker",
    route: "Oral",
    price: 210.0
  },
  {
    name: "Proscar 5mg Tablet",
    activeIngredient: "Finasteride",
    manufacturer: "MSD",
    category: "Urology",
    strength: "5mg",
    form: "أقراص لعلاج تضخم البروستاتا الحميد",
    therapeuticClass: "5-Alpha Reductase Inhibitor",
    route: "Oral",
    price: 160.0
  },
  {
    name: "Cardura 4mg Tablet",
    activeIngredient: "Doxazosin Mesylate",
    manufacturer: "Pfizer",
    category: "Urology",
    strength: "4mg",
    form: "أقراص لعلاج ضغط الدم وتضخم البروستاتا",
    therapeuticClass: "Alpha-1 Adrenergic Blocker",
    route: "Oral",
    price: 85.0
  },
  {
    name: "Vesicare 5mg Tablet",
    activeIngredient: "Solifenacin Succinate",
    manufacturer: "Astellas",
    category: "Urology",
    strength: "5mg",
    form: "أقراص لعلاج المثانة النشطة وكثرة التبول",
    therapeuticClass: "Urinary Antispasmodic / Anticholinergic",
    route: "Oral",
    price: 165.0
  },
  {
    name: "Vesicare 10mg Tablet",
    activeIngredient: "Solifenacin Succinate",
    manufacturer: "Astellas",
    category: "Urology",
    strength: "10mg",
    form: "أقراص لعلاج المثانة النشطة وكثرة التبول",
    therapeuticClass: "Urinary Antispasmodic / Anticholinergic",
    route: "Oral",
    price: 220.0
  },

  // === Category: Neuropsychiatric & Muscle Relaxants (باسط العضلات والأعصاب والنفسية) ===
  {
    name: "Dimra Tablet",
    activeIngredient: "Methocarbamol / Diclofenac Potassium",
    manufacturer: "Sedico",
    category: "Neuro",
    strength: "500mg/50mg",
    form: "أقراص باسطة للعضلات ومسكنة للألم",
    therapeuticClass: "Skeletal Muscle Relaxant & NSAID",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Myolgin Tablet",
    activeIngredient: "Chlorzoxazone / Paracetamol",
    manufacturer: "Amriya",
    category: "Neuro",
    strength: "250mg/300mg",
    form: "أقراص باسطة للعضلات ومسكنة ومضادة للالتهاب",
    therapeuticClass: "Skeletal Muscle Relaxant & Analgesic",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Parafon Tablet",
    activeIngredient: "Chlorzoxazone / Acetaminophen (Paracetamol)",
    manufacturer: "MUP",
    category: "Neuro",
    strength: "250mg/300mg",
    form: "أقراص مسكنة وباسطة للعضلات",
    therapeuticClass: "Skeletal Muscle Relaxant & Analgesic",
    route: "Oral",
    price: 32.0
  },
  {
    name: "Lioresal 10mg Tablet",
    activeIngredient: "Baclofen",
    manufacturer: "Novartis",
    category: "Neuro",
    strength: "10mg",
    form: "أقراص باسطة للعضلات وتشنجات الحبل الشوكي",
    therapeuticClass: "Centrally Acting Muscle Relaxant",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Tegretol 200mg Tablet",
    activeIngredient: "Carbamazepine",
    manufacturer: "Novartis",
    category: "Neuro",
    strength: "200mg",
    form: "أقراص لعلاج الصرع وآلام الأعصاب",
    therapeuticClass: "Anticonvulsant / Antiepileptic",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Tegretol CR 400mg",
    activeIngredient: "Carbamazepine",
    manufacturer: "Novartis",
    category: "Neuro",
    strength: "400mg",
    form: "أقراص ممتدة المفعول لعلاج الصرع",
    therapeuticClass: "Anticonvulsant / Antiepileptic",
    route: "Oral",
    price: 98.0
  },
  {
    name: "Depakine Chrono 500mg",
    activeIngredient: "Sodium Valproate / Valproic Acid",
    manufacturer: "Sanofi",
    category: "Neuro",
    strength: "500mg",
    form: "أقراص لعلاج الصرع ونوبات الهوس",
    therapeuticClass: "Anticonvulsant / Mood Stabilizer",
    route: "Oral",
    price: 135.0
  },
  {
    name: "Neurontin 300mg Capsule",
    activeIngredient: "Gabapentin",
    manufacturer: "Pfizer",
    category: "Neuro",
    strength: "300mg",
    form: "كبسولات لعلاج الصرع وآلام الأعصاب الطرفية",
    therapeuticClass: "Gabapentinoid / Antineuropathic Pain",
    route: "Oral",
    price: 156.0
  },
  {
    name: "Neurontin 400mg Capsule",
    activeIngredient: "Gabapentin",
    manufacturer: "Pfizer",
    category: "Neuro",
    strength: "400mg",
    form: "كبسولات لعلاج الصرع وآلام الأعصاب الطرفية",
    therapeuticClass: "Gabapentinoid / Antineuropathic Pain",
    route: "Oral",
    price: 195.0
  },
  {
    name: "Lyrica 75mg Capsule",
    activeIngredient: "Pregabalin",
    manufacturer: "Pfizer",
    category: "Neuro",
    strength: "75mg",
    form: "كبسولات لعلاج آلام الأعصاب والقلق العام والصرع",
    therapeuticClass: "Gabapentinoid / Controlled Drug",
    route: "Oral",
    price: 180.0
  },
  {
    name: "Lyrica 150mg Capsule",
    activeIngredient: "Pregabalin",
    manufacturer: "Pfizer",
    category: "Neuro",
    strength: "150mg",
    form: "كبسولات لعلاج آلام الأعصاب والقلق العام",
    therapeuticClass: "Gabapentinoid / Controlled Drug",
    route: "Oral",
    price: 240.0
  },
  {
    name: "Cipralex 10mg Tablet",
    activeIngredient: "Escitalopram Oxalate",
    manufacturer: "Lundbeck",
    category: "Neuro",
    strength: "10mg",
    form: "أقراص مضادة للاكتئاب والقلق والوسواس",
    therapeuticClass: "Antidepressant (SSRI)",
    route: "Oral",
    price: 190.0
  },
  {
    name: "Cymbalta 60mg Capsule",
    activeIngredient: "Duloxetine Hydrochloride",
    manufacturer: "Lilly",
    category: "Neuro",
    strength: "60mg",
    form: "كبسولات لعلاج الاكتئاب وآلام الأعصاب السكري والمفاصل",
    therapeuticClass: "Antidepressant (SNRI) / Neuropathic Pain",
    route: "Oral",
    price: 260.0
  },
  {
    name: "Prozac 20mg Capsule",
    activeIngredient: "Fluoxetine Hydrochloride",
    manufacturer: "Lilly",
    category: "Neuro",
    strength: "20mg",
    form: "كبسولات لعلاج الاكتئاب والوسواس القهري",
    therapeuticClass: "Antidepressant (SSRI)",
    route: "Oral",
    price: 150.0
  },
  {
    name: "Faverin 100mg Tablet",
    activeIngredient: "Fluvoxamine Maleate",
    manufacturer: "Abbott",
    category: "Neuro",
    strength: "100mg",
    form: "أقراص لعلاج الاكتئاب والوسواس القهري الشديد",
    therapeuticClass: "Antidepressant (SSRI / Potent Anti-OCD)",
    route: "Oral",
    price: 165.0
  },
  {
    name: "Amigraine ADCO Tablet",
    activeIngredient: "Analgin / Caffeine / Ergotamine Tartrate / Belladonna Alkaloids",
    manufacturer: "ADCO",
    category: "Neuro",
    strength: "Complex",
    form: "أقراص لعلاج نوبات الصداع النصفي الشديدة",
    therapeuticClass: "Migraine Remedy",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Imigran 50mg Tablet",
    activeIngredient: "Sumatriptan Suppress",
    manufacturer: "GSK",
    category: "Neuro",
    strength: "50mg",
    form: "أقراص مخصصة لوقف نوبة الصداع النصفي الحادة",
    therapeuticClass: "Triptan / Potent Anti-Migraine",
    route: "Oral",
    price: 90.0
  },

  // === Category: Gynecological & Obstetric (أدوية أمراض النساء والتوليد) ===
  {
    name: "Cyclo-Progynova",
    activeIngredient: "Estradiol Valerate / Norgestrel",
    manufacturer: "Bayer",
    category: "Gynecology",
    strength: "2mg/0.5mg",
    form: "أقراص هرمونية لتنظيم الدورة الشهرية",
    therapeuticClass: "Hormone Replacement Therapy (HRT)",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Yasmin Tablet",
    activeIngredient: "Drospirenone / Ethinyl Estradiol",
    manufacturer: "Bayer",
    category: "Gynecology",
    strength: "3mg/0.03mg",
    form: "أقراص لمنع الحمل وتنظيم الهرمونات",
    therapeuticClass: "Oral Contraceptive Pill",
    route: "Oral",
    price: 95.0
  },
  {
    name: "Gynera Tablet",
    activeIngredient: "Gestodene / Ethinyl Estradiol",
    manufacturer: "Bayer",
    category: "Gynecology",
    strength: "0.075mg/0.03mg",
    form: "أقراص لمنع الحمل وتنظيم الدورة",
    therapeuticClass: "Oral Contraceptive Pill",
    route: "Oral",
    price: 75.0
  },
  {
    name: "Primolut Nor 5mg",
    activeIngredient: "Norethisterone",
    manufacturer: "Bayer",
    category: "Gynecology",
    strength: "5mg",
    form: "أقراص لتنظيم أو تأخير الدورة الشهرية وعلاج النزيف",
    therapeuticClass: "Progestogen Hormone",
    route: "Oral",
    price: 45.0
  },
  {
    name: "Duphaston 10mg",
    activeIngredient: "Dydrogesterone",
    manufacturer: "Abbott",
    category: "Gynecology",
    strength: "10mg",
    form: "أقراص لتثبيت الحمل وتنظيم الدورة الشهرية",
    therapeuticClass: "Progesterone Analog / Pregnancy Support",
    route: "Oral",
    price: 160.0
  },
  {
    name: "Elevit Pronatal Tablet",
    activeIngredient: "Comprehensive Vitamins & Minerals for Pregnancy",
    manufacturer: "Bayer",
    category: "Gynecology",
    strength: "Complex",
    form: "أقراص فيتامينات متكاملة للحامل والمرضع",
    therapeuticClass: "Prenatal Multivitamin",
    route: "Oral",
    price: 195.0
  },
  {
    name: "Gynoflor Vaginal Tablet",
    activeIngredient: "Lactobacillus acidophilus / Estriol",
    manufacturer: "March",
    category: "Gynecology",
    strength: "50mg/0.03mg",
    form: "أقراص مهبلية لاستعادة فلورا المهبل الطبيعية وعلاج الالتهابات",
    therapeuticClass: "Vaginal Antiseptic & Restorer",
    route: "Vaginal",
    price: 68.0
  },

  // === Category: Gastrointestinal Extra & Anti-spasmodic (أدوية إضافية للجهاز الهضمي والتقلصات) ===
  {
    name: "Buscopan 10mg Tablet",
    activeIngredient: "Hyoscine Butylbromide",
    manufacturer: "Sanofi",
    category: "Gastrointestinal",
    strength: "10mg",
    form: "أقراص مهدئة للمغص والتقلصات",
    therapeuticClass: "Antispasmodic / Anticholinergic",
    route: "Oral",
    price: 36.0
  },
  {
    name: "Buscopan Plus Tablet",
    activeIngredient: "Hyoscine Butylbromide / Paracetamol",
    manufacturer: "Sanofi",
    category: "Gastrointestinal",
    strength: "10mg/500mg",
    form: "أقراص لعلاج المغص الحاد والآلام المصاحبة",
    therapeuticClass: "Antispasmodic & Analgesic",
    route: "Oral",
    price: 48.0
  },
  {
    name: "Buscopan Ampoule 20mg",
    activeIngredient: "Hyoscine Butylbromide",
    manufacturer: "Sanofi",
    category: "Gastrointestinal",
    strength: "20mg/1ml",
    form: "حقن لعلاج حالات المغص والتقلصات الحادة",
    therapeuticClass: "Antispasmodic Injection",
    route: "Intravenous / Intramuscular / Subcutaneous",
    price: 40.0
  },
  {
    name: "Gastrobiotic 550mg",
    activeIngredient: "Rifaximin",
    manufacturer: "Eva Pharma",
    category: "Gastrointestinal",
    strength: "550mg",
    form: "أقراص مطهرة للقولون ومضاد حيوي لا يمتص",
    therapeuticClass: "Non-systemic GI Antibiotic / IBS Treatment",
    route: "Oral",
    price: 195.0
  },
  {
    name: "Lacteol Fort Capsule",
    activeIngredient: "Lactobacillus acidophilus (Lactobacillus LB)",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "10 Billion Organisms",
    form: "كبسولات لتعويض البكتيريا النافعة وعلاج الإسهال والقولون",
    therapeuticClass: "Antidiarrheal Probiotic",
    route: "Oral",
    price: 52.0
  },
  {
    name: "Smecta Powder Sachet",
    activeIngredient: "Dioctahedral Smectite (Diosmectite)",
    manufacturer: "Amriya",
    category: "Gastrointestinal",
    strength: "3g",
    form: "أكياس فوار معلق لعلاج الإسهال الحاد",
    therapeuticClass: "Intestinal Adsorbent / Antidiarrheal",
    route: "Oral (After suspension in water)",
    price: 45.0
  },
  {
    name: "Colona Tablet",
    activeIngredient: "Mebeverine Hydrochloride / Sulpiride",
    manufacturer: "Rameda",
    category: "Gastrointestinal",
    strength: "100mg/25mg",
    form: "أقراص لعلاج القولون العصبي المصحوب بالقلق والتوتر",
    therapeuticClass: "Antispasmodic & Neuroleptic Combination",
    route: "Oral",
    price: 40.0
  },
  {
    name: "Legalon 140mg Capsule",
    activeIngredient: "Silymarin (Milk Thistle Extract)",
    manufacturer: "SEDICO",
    category: "Gastrointestinal",
    strength: "140mg",
    form: "كبسولات مكملة لحماية خلايا الكبد وتنشيطها",
    therapeuticClass: "Hepatoprotective / Liver Supplement",
    route: "Oral",
    price: 55.0
  },
  {
    name: "Essentiale Forte Capsule",
    activeIngredient: "Essential Phospholipids",
    manufacturer: "Sanofi",
    category: "Gastrointestinal",
    strength: "300mg",
    form: "كبسولات منشطة لوظائف خلايا الكبد وعلاج الدهون عليه",
    therapeuticClass: "Hepatoprotective agent",
    route: "Oral",
    price: 90.0
  }
];

async function main() {
  console.log(`Starting to seed ${medications.length} famous medications...`);
  
  let insertedCount = 0;
  for (const med of medications) {
    try {
      await prisma.medication.upsert({
        where: { name: med.name },
        update: {
          activeIngredient: med.activeIngredient,
          manufacturer: med.manufacturer,
          category: med.category,
          strength: med.strength,
          form: med.form,
          therapeuticClass: med.therapeuticClass,
          route: med.route,
          price: med.price,
          isGlobal: true
        },
        create: {
          name: med.name,
          activeIngredient: med.activeIngredient,
          manufacturer: med.manufacturer,
          category: med.category,
          strength: med.strength,
          form: med.form,
          therapeuticClass: med.therapeuticClass,
          route: med.route,
          price: med.price,
          isGlobal: true
        }
      });
      insertedCount++;
    } catch (err) {
      console.error(`Failed to seed ${med.name}:`, err.message);
    }
  }

  console.log(`Successfully seeded ${insertedCount} medications to the database!`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
